### ISSUE TITLE
custom vue components

### ISSUE THREAD

**Issue by jannikbuscha** [yeikiu/vue3-md-blog#7]
Hi, is it possible to specify custom vue components in the markdown file that will be rendered afterwards? e.g. `<my-button>Hi</my-button>` will then become `<a class="btn">Hi</a>` as html element

**Comment by yeikiu** [comment]
> Hi, is it possible to specify custom vue components in the markdown file that will be rendered afterwards? e.g. `<my-button>Hi</my-button>` will then become `<a class="btn">Hi</a>` as html element

Sorry I didn't get to you earlier, been lost in other projects tbh. You won't be able to do that from the posts .md files but you could technically define minimal components within `vue3-md-blog/src/components` as `MyCustomButton.md` as long as they don't need any kind of setup or js logic in general.
