### ISSUE TITLE
How to enable syntax highlighting?

### ISSUE THREAD

**Issue by MSoup** [yeikiu/vue3-md-blog#8]
Hi there, it looks like the template says that syntax highlighting is supported, but I'm not finding a way to implement it. 

The markdown-it documentation suggests that we need to wrap our markdown with
'highlight.js'. 

I found [this solution](https://github.com/nuxt-community/markdownit-module/issues/8) which involves adding rules to nuxt.config, but this project doesn't seem to use nuxt. 

The markdown-it documentation also provides this example

```js
var hljs = require('highlight.js'); // https://highlightjs.org

// Actual default values
var md = require('markdown-it')({
  highlight: function (str, lang) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(str, { language: lang }).value;
      } catch (__) {}
    }

    return ''; // use external default escaping
  }
});
```

However, the way that the template imports the markdown looks like this

`const markDownIt = new MarkdownIt({ html: true }).use(emoji)`

`const postHtml = markDownIt.render(markDownSource)`

How would I wrap the postHtml with the highlighter and subsequently apply the github hightlighting rules to it?

**Comment by MSoup** [comment]
I figured it out! For any other newbies wishing to get syntax highlighting working, here are the steps:
1. Get highlightjs: `npm install highlight.js`
2. Import it into `views/Post.vue`, like `import hljs from 'highlight.js';`
3. Don't forget to add the required css: `import 'highlight.js/styles/github.css';`
4. A MarkdownIt object accepts `highlight` as a possible option, so add it alongside the existing `html: true`.

### Before
`const markDownIt = new MarkdownIt({ html: true }).use(emoji)`

### After

```js
const markDownIt = new MarkdownIt({
  html: true,
  highlight: function (str: string, lang: string) {
    if (lang && hljs.getLanguage(lang)) {
      try {
        return hljs.highlight(str, { language: lang }).value;
      } catch (__) { }
    }

    return ''; // use external default escaping
  }
}).use(emoji)
```

This should be enough to provide syntax highlighting into the starter app!

**Comment by yeikiu** [comment]
This would be a great pull-request if you are willing to submit it!

**Comment by MSoup** [comment]
Hello, thanks for getting back to me.

I'd be happy to submit it! Please allow me a few days :)

I also have a few other proposed changes, but you are free to do what you will with them:

- the way the menu bar opens and closes by default is a little clunky. It makes sense to be able to close the dropdown menu when we click outside the menu. The problem is that there aren't really any clean solutions for this. Solutions I thought of were:

1. We'd need to apply an event listener on the whole window and listen for clicks outside the dropdown when the dropdown is active. I don't really like this approach because it's always going to be firing
2. Make the dropdown a full page modal where the rest of the page is just a div that takes up the whole screen, but isn't visible. Now the event listener can be added to the div

**Comment by yeikiu** [comment]
Hey man!

Thanks for the good feedback. I've created a PR for the menu fix in case you want to review it: https://github.com/yeikiu/vue3-md-blog/pull/10

I'll be happy to add you code highlighting contribution once you submit it, no rush.

Happy hacking!
