### ISSUE TITLE
Workflow failing at `Run rm -rf .ci_badges`, maybe I am releasing incorrectly?

### ISSUE THREAD

**Issue by MSoup** [yeikiu/vue3-md-blog#9]
I realized that the dist was not automatically building on push to master, and upon further investigation it turns out I needed to `release`. It's my first time doing so, so I might be handling it incorrectly. 

Steps to reproduce:
- go to the sidebar in my repository titled "Releases"
- choose a tag (I chose v0.1.2)
- publish

Errors:
Upon looking at my workflow, it seems dist is not created because it fails at the below:

```
Run rm -rf .ci_badges
npm WARN exec The following package was not found and will be installed: setup-gh-badges@2.0.4


✔️   msoup-blog v3.1.9: Badges updated successfully!
    
    # version 3.1.9
    # dependencies 8
    # devDependencies 8


HEAD detached at v0.1.2
nothing to commit, working tree clean
Error: Process completed with exit code 1.
```

Would someone be able to provide any hints?

I have a feeling that `HEAD detached at v0.1.2` is probably a big hint, but I'm unsure why this is happening.

**Comment by yeikiu** [comment]
Hello there!

```
> Run rm -rf .ci_badges
> npm WARN exec The following package was not found and will be installed: setup-gh-badges@2.0.4
```

Did you remove the `.ci_badges` directory from the root maybe? The workflow expects it to exist under `.github/workflows/deploy_to_gh_pages.yml` line #16

If you check the guide under https://yeikiu.github.io/vue3-md-blog/#/guide/setup-yor-own-blog and make sure your pages config for the repo are configured to use the branch `gh-pages` you should be good.

You only need to _Generate a GitHub release_ if you change code/functionality. Changing markdown content for posts and pushing to master will automatically update just the content saving the whole build+deploy process.

Hope this helps.

**Comment by yeikiu** [comment]
I think you solved the issues after seeing the nice work under https://msoup.github.io/msoup-blog/#/5-minute-series 

kudos!

Happily closing the thread :)
